branch-defaults:
  dev:
    environment: udagram-krasserp-image-filter-dev-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-krasserp-image-filter-dev
  branch: null
  default_ec2_keyname: udagram-krasserp
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: udagram-phil-dev
  repository: null
  sc: git
  workspace_type: Application
